"""remove location column

Revision ID: 7e476b12f77e
Revises: 2c77b0f888b7
Create Date: 2025-04-30 12:44:35.380159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e476b12f77e'
down_revision = '2c77b0f888b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
