"""Refined fetchign data

Revision ID: c8a2ca36b00f
Revises: 2d16f70f4a15
Create Date: 2025-04-30 11:27:57.830178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a2ca36b00f'
down_revision = '2d16f70f4a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cities', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience_levels', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sectors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('tags')
        batch_op.drop_column('sectors')
        batch_op.drop_column('experience_levels')
        batch_op.drop_column('cities')

    # ### end Alembic commands ###
